# Generated by Django 5.0.2 on 2024-02-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
