# Generated by Django 4.0.3 on 2024-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_attendance_remove_clockin_user_delete_breakin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='break_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='break_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
