# Generated by Django 4.0.3 on 2024-05-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_attendance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='lunchin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lunchout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
