# Generated by Django 4.0.3 on 2024-05-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_lunchin_lunchout_timein_timeout_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='clicked_at',
            field=models.TimeField(null=True),
        ),
    ]
