# Generated by Django 5.0.4 on 2024-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_clicked_at_timein_clicked_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchin',
            name='clicked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunchin',
            name='clicked_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunchout',
            name='clicked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunchout',
            name='clicked_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='clicked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='clicked_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='clicked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='clicked_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
