# Generated by Django 5.0.4 on 2024-05-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_lunchin_user_lunchout_user_timein_user_timeout_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunchout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timein',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeout',
            name='user',
        ),
    ]
